-- 2.10.2026: Leijonat- ja NHL-visoille oikeat valokuvat (Heikki: julkaise vahvat, heikot eli nuorten kullat odottavat;
-- olympiakulta 2022:lle ei löytynyt vapaata kuvaa). Sama kuva on Jääkiekko-kokoelman kortissa. Lähteet lib/kuvalahteet.ts.
update quizzes set hero_image = '/20/jaakiekko/jk-leijonat-mm1995-kuva.webp', hero_focal_x = 0.4, hero_focal_y = 0.5, hero_alt = 'Jääkiekon maailmanmestaruusriehaa Helsingin Esplanadilla tunti finaalin jälkeen 7.5.1995. Kuva: Matti Niemi / Helsingin kaupunginmuseo / Wikimedia Commons, CC BY 4.0' where slug = 'leijonat-mm-1995-kulta';
update quizzes set hero_image = '/20/jaakiekko/jk-leijonat-mm2011-kuva.webp', hero_focal_x = 0.7, hero_focal_y = 0.5, hero_alt = 'Mikael Granlund ja Teemu Lassila MM-kultajuhlissa Helsingissä 16.5.2011. Kuva: Tuomas Puikkonen / Wikimedia Commons, CC BY 2.0' where slug = 'leijonat-mm-2011-kulta';
update quizzes set hero_image = '/20/jaakiekko/jk-leijonat-mm2019-kuva.webp', hero_focal_x = 0.4, hero_focal_y = 0.5, hero_alt = 'MM-kullan juhlintaa Helsingin Kauppatorilla toukokuussa 2019. Kuva: Kissa21782 / Wikimedia Commons, CC BY-SA 4.0' where slug = 'leijonat-mm-2019-kulta';
update quizzes set hero_image = '/20/jaakiekko/jk-leijonat-mm2022-kuva.webp', hero_focal_x = 0.4, hero_focal_y = 0.5, hero_alt = 'Juhlijat Kauppatorin raitiovaunupysäkin katolla MM-kullan jälkeen 29.5.2022. Kuva: Ximonic (Simo Räsänen) / Wikimedia Commons, CC BY-SA 4.0' where slug = 'leijonat-mm-2022-kulta';
update quizzes set hero_image = '/20/jaakiekko/jk-leijonat-mm2026-kuva.webp', hero_focal_x = 0.7, hero_focal_y = 0.5, hero_alt = 'Suomi–Iso-Britannia-ottelu jääkiekon MM-kisoissa Zürichissä 22.5.2026. Kuva: Albinfo / Wikimedia Commons, CC BY-SA 4.0' where slug = 'leijonat-mm-2026-kulta';
update quizzes set hero_image = '/20/jaakiekko/jk-nhl-pioneerit-kuva.webp', hero_focal_x = 0.4, hero_focal_y = 0.5, hero_alt = 'Suomen jääkiekkomaajoukkueen pelaajia ottelun jälkeen Tampereella 1969. Kuva: Tuntematon / Helsingin Sanomat / Wikimedia Commons, public domain' where slug = 'suomalaiset-nhl-pioneerit';
update quizzes set hero_image = '/20/jaakiekko/jk-nhl-ennatykset-kuva.webp', hero_focal_x = 0.36, hero_focal_y = 0.5, hero_alt = 'Teemu Selänne Saksaa vastaan Vancouverin olympialaisissa 2010. Kuva: s.yume / Wikimedia Commons, CC BY 2.0' where slug = 'suomalaiset-nhl-ennatykset';
update quizzes set hero_image = '/20/jaakiekko/jk-nhl-kuriositeetit-kuva.webp', hero_focal_x = 0.4, hero_focal_y = 0.5, hero_alt = 'NHL-kauden 2010–11 avausaloitus Helsingissä: Mikko Koivu (Minnesota Wild) vastaan Carolina Hurricanes 7.10.2010. Kuva: Saruwine / Wikimedia Commons, CC BY-SA 3.0' where slug = 'suomalaiset-nhl-kuriositeetit';
