-- 2.10.2026: Liigan yleisvisoille oikeat valokuvat (Heikin valinnat Riksman, Jalonen, Ruutu, Moberg + vahvat).
-- Maalitykit odottaa (Esa Peltonen -kuvan lisenssi epävarma). Lähteet lib/kuvalahteet.ts.
update quizzes set hero_image = '/20/jaakiekko/jk-liiga-maalivahdit-kuva.webp', hero_focal_x = 0.4, hero_focal_y = 0.1, hero_alt = 'HIFK:n maalivahti Juuso Riksman 2011. Kuva: JimmyK / Wikimedia Commons, CC BY-SA 3.0' where slug = 'sm-liiga-maalivahtilegendat';
update quizzes set hero_image = '/20/jaakiekko/jk-liiga-pistekuninkaat-kuva.webp', hero_focal_x = 0.4, hero_focal_y = 0.1, hero_alt = 'Liigan kaikkien aikojen pistekuningas Raimo Helminen (Ilves) SaiPaa vastaan 2007. Kuva: Saruwine / Wikimedia Commons, CC BY-SA 4.0' where slug = 'sm-liiga-kaikkien-aikojen-pistekuninkaat';
update quizzes set hero_image = '/20/jaakiekko/jk-liiga-finaalidraamat-kuva.webp', hero_focal_x = 0.4, hero_focal_y = 0.1, hero_alt = 'Kanada-malja, Liigan mestaruuspokaali. Kuva: Lasse Keskinen / Wikimedia Commons, CC BY-SA 4.0' where slug = 'sm-liiga-finaalidraamat';
update quizzes set hero_image = '/20/jaakiekko/jk-liiga-valmentajat-kuva.webp', hero_focal_x = 0.4, hero_focal_y = 0.1, hero_alt = 'Valmentaja Kari Jalonen vaihtopenkin takana 2012. Kuva: Artem Korzhimanov / Wikimedia Commons, CC BY-SA 3.0' where slug = 'sm-liiga-valmentajadraamat-tulisielut';
update quizzes set hero_image = '/20/jaakiekko/jk-liiga-ulkomaalaiset-kuva.webp', hero_focal_x = 0.4, hero_focal_y = 0.1, hero_alt = 'SaiPan kanadalaisvahvistus Dale McTavish Tapparaa vastaan 2010. Kuva: Tuomas Vitikainen / Wikimedia Commons, CC BY-SA 3.0' where slug = 'sm-liiga-ulkomaalaisvahvistukset';
update quizzes set hero_image = '/20/jaakiekko/jk-liiga-pomot-kuva.webp', hero_focal_x = 0.4, hero_focal_y = 0.08, hero_alt = 'Jääkiekon ammattilaishankkeen miehet Timo Haapaniemi, Aimo Mäkinen, Göran Stubb ja Frank Moberg 14.3.1973. Kuva: Museovirasto, JOKA Journalistinen kuva-arkisto (HBL), CC BY 4.0' where slug = 'sm-liigan-legendaariset-pomot-visa';
update quizzes set hero_image = '/20/jaakiekko/jk-liiga-kovanaamat-kuva.webp', hero_focal_x = 0.4, hero_focal_y = 0.1, hero_alt = 'Jokereiden Jarkko Ruutu SaiPaa vastaan Lappeenrannassa 2013. Kuva: Tuomas Vitikainen / Wikimedia Commons, CC BY-SA 3.0' where slug = 'sm-liiga-jaahykuninkaat-kovanaamat';
update quizzes set hero_image = '/20/jaakiekko/jk-liiga-tuomarit-kuva.webp', hero_focal_x = 0.4, hero_focal_y = 0.1, hero_alt = 'Erotuomari Tom Laaksonen ja linjatuomari Jussi Terho SM-liigaottelussa 2007. Kuva: Saruwine / Wikimedia Commons, CC BY-SA 4.0' where slug = 'sm-liiga-tuomarilegendat';
