-- 1.10.2026: joukkuevisoille oikeat valokuvat AI-kuvien tilalle (Heikki hyväksyi; KooKoo erikseen 20261019).
-- Sama kuva on Jääkiekko-kokoelman seurakortissa. Lähteet lib/kuvalahteet.ts:ssä.
update quizzes set hero_image = '/20/jaakiekko/jk-tappara-kuva.webp', hero_focal_x = 0.7, hero_focal_y = 0.5, hero_alt = 'Tapparan pelaajat Nokia Arenan avausottelussa 3.12.2021. Kuva: kallerna / Wikimedia Commons, CC BY-SA 4.0' where slug = 'tappara-tampere-kirvesrinnat-tietovisa';
update quizzes set hero_image = '/20/jaakiekko/jk-ilves-kuva.webp', hero_focal_x = 0.36, hero_focal_y = 0.5, hero_alt = 'Raimo Helminen Ilveksen vuoden 1985 retropaidassa viimeisen runkosarjaottelunsa jälkeen 2008. Kuva: Saruwine / Wikimedia Commons, CC BY-SA 3.0' where slug = 'ilves-tampere-keltamustat-tietovisa';
update quizzes set hero_image = '/20/jaakiekko/jk-tps-kuva.webp', hero_focal_x = 0.7, hero_focal_y = 0.5, hero_alt = 'TPS:n Marko Kiprusoff tammikuussa 2008. Kuva: Saruwine / Wikimedia Commons, CC BY-SA 4.0' where slug = 'tps-turku-jaakiekko-tietovisa';
update quizzes set hero_image = '/20/jaakiekko/jk-karpat-kuva.webp', hero_focal_x = 0.4, hero_focal_y = 0.5, hero_alt = 'Kärppien Juha-Pekka Haataja vierasottelussa Lappeenrannassa 2012. Kuva: Tuomas Vitikainen / Wikimedia Commons, CC BY-SA 3.0' where slug = 'karpat-tietovisa-legendat';
update quizzes set hero_image = '/20/jaakiekko/jk-hifk-kuva.webp', hero_focal_x = 0.4, hero_focal_y = 0.5, hero_alt = 'HIFK:n Siim Liivik SaiPaa vastaan Lappeenrannassa 2010. Kuva: Tuomas Vitikainen / Wikimedia Commons, CC BY-SA 3.0' where slug = 'hifk-helsinki-punavalkoiset-tietovisa';
update quizzes set hero_image = '/20/jaakiekko/jk-jokerit-kuva.webp', hero_focal_x = 0.7, hero_focal_y = 0.5, hero_alt = 'Jokereiden pelaajat juhlivat pudotuspelivoittoa Helsingissä maaliskuussa 2026. Kuva: Quintin Soloviev / Wikimedia Commons, CC BY 4.0' where slug = 'jokerit-helsinki-liigahistoria-tietovisa';
update quizzes set hero_image = '/20/jaakiekko/jk-assat-kuva.webp', hero_focal_x = 0.4, hero_focal_y = 0.5, hero_alt = 'Ässät juhlii voittoa kotiyleisön edessä Porissa 2023. Kuva: Kilaseell / Wikimedia Commons, CC BY-SA 4.0' where slug = 'assat-isomaen-ukkoset-tietovisa';
update quizzes set hero_image = '/20/jaakiekko/jk-hpk-kuva.webp', hero_focal_x = 0.4, hero_focal_y = 0.5, hero_alt = 'HPK:n pelaajat Ilvestä vastaan Tampere Cupissa 2021. Kuva: Piquito / Wikimedia Commons, CC BY-SA 4.0' where slug = 'hpk-rinkelinmaen-ritarit-tietovisa';
update quizzes set hero_image = '/20/jaakiekko/jk-lukko-kuva.webp', hero_focal_x = 0.4, hero_focal_y = 0.5, hero_alt = 'Lukon pelaaja Champions Hockey Leaguen ottelussa Berliinissä syyskuussa 2025. Kuva: Sandro Halank / Wikimedia Commons, CC BY-SA 4.0' where slug = 'rauman-lukko-visa';
update quizzes set hero_image = '/20/jaakiekko/jk-jyp-kuva.webp', hero_focal_x = 0.36, hero_focal_y = 0.5, hero_alt = 'JYP:n maalivahti Sinuhe Wallinheimo lokakuussa 2007. Kuva: Saruwine / Wikimedia Commons, CC BY-SA 4.0' where slug = 'jyp-hippoksen-hurmaa-tietovisa';
update quizzes set hero_image = '/20/jaakiekko/jk-kalpa-kuva.webp', hero_focal_x = 0.4, hero_focal_y = 0.5, hero_alt = 'KalPan Jukka Hentunen vierasottelussa Lappeenrannassa 2011. Kuva: Tuomas Vitikainen / Wikimedia Commons, CC BY-SA 3.0' where slug = 'kalpa-niiralan-montun-kovin-tietovisa';
update quizzes set hero_image = '/20/jaakiekko/jk-pelicans-kuva.webp', hero_focal_x = 0.36, hero_focal_y = 0.5, hero_alt = 'Pelicansin Jyri Marttinen Ilvestä vastaan Tampereella 2011. Kuva: Saruwine / Wikimedia Commons, CC BY-SA 3.0' where slug = 'pelicans-kolme-kertaa-hopealla-tietovisa';
update quizzes set hero_image = '/20/jaakiekko/jk-saipa-kuva.webp', hero_focal_x = 0.4, hero_focal_y = 0.5, hero_alt = 'SaiPan Miikka Salomäki laukoo Pelicansia vastaan Kisapuistossa 7.3.2026. Kuva: Alluvisuals / Wikimedia Commons, CC BY 4.0' where slug = 'saipa-saimaan-syketta-tietovisa';
update quizzes set hero_image = '/20/jaakiekko/jk-sport-kuva.webp', hero_focal_x = 0.4, hero_focal_y = 0.5, hero_alt = 'Aloitus ottelussa Vaasan Sport – Rauman Lukko helmikuussa 2022. Kuva: Tero Lahtinen / Wikimedia Commons, CC BY 2.0' where slug = 'sport-punavalkoinen-tarina-tietovisa';
update quizzes set hero_image = '/20/jaakiekko/jk-jukurit-kuva.webp', hero_focal_x = 0.4, hero_focal_y = 0.5, hero_alt = 'Aloitus Jukurien ja KalPan ottelussa Mikkelissä 26.12.2016. Kuva: Pruthus / Wikimedia Commons, CC BY-SA 4.0' where slug = 'jukurit-sisasavolaista-sisua-tietovisa';
update quizzes set hero_image = '/20/jaakiekko/jk-kiekko-espoo-kuva.webp', hero_focal_x = 0.36, hero_focal_y = 0.5, hero_alt = 'Espoo Bluesin Stefan Öhman 2010 – Kiekko-Espoon edeltäjäseura. Kuva: Vieldor / Wikimedia Commons, CC BY-SA 3.0' where slug = 'kiekko-espoo-tuhkasta-liigaan-tietovisa';
